name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test

  deploy:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: s0/git--publish-subdir-action@v1.0.0
        env:
          REPO: ${{ secrets.DEPLOY_GIT_REPO }}
          BRANCH: master
          FOLDER: .
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          KNOWN_HOSTS_FILE: resources/known_hosts
